import type { Product, DealProduct } from "@/types/products";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Pipely Enterprise License",
    code: "PIP-ENT-001",
    description: "Licenza annuale per Pipely Enterprise con supporto illimitato",
    category: "LICENSE",
    unitPrice: 2400,
    currency: "EUR",
    taxRate: 22,
    unit: "anno",
    isActive: true,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "prod-2",
    name: "Consulenza implementazione",
    code: "SVC-IMP-001",
    description: "Servizio di consulenza per implementazione e configurazione",
    category: "SERVICE",
    unitPrice: 150,
    currency: "EUR",
    taxRate: 22,
    unit: "ora",
    isActive: true,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "prod-3",
    name: "Supporto Premium",
    code: "SUP-PRE-001",
    description: "Piano di supporto premium con SLA garantito 4h",
    category: "SUPPORT",
    unitPrice: 800,
    currency: "EUR",
    taxRate: 22,
    unit: "mese",
    isActive: true,
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "prod-4",
    name: "Modulo Marketing Automation",
    code: "MOD-MKT-001",
    description: "Add-on per automazione campagne marketing",
    category: "SOFTWARE",
    unitPrice: 500,
    currency: "EUR",
    taxRate: 22,
    unit: "mese",
    isActive: true,
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "prod-5",
    name: "Server Dedicato",
    code: "HW-SRV-001",
    description: "Server dedicato on-premise per installazione locale",
    category: "HARDWARE",
    unitPrice: 4500,
    currency: "EUR",
    taxRate: 22,
    unit: "pezzo",
    isActive: true,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "prod-6",
    name: "Formazione utenti",
    code: "SVC-TRN-001",
    description: "Sessione di formazione per team sales (max 10 persone)",
    category: "SERVICE",
    unitPrice: 600,
    currency: "EUR",
    taxRate: 22,
    unit: "giornata",
    isActive: true,
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "prod-7",
    name: "API Access Token",
    code: "SW-API-001",
    description: "Token di accesso API per integrazioni personalizzate",
    category: "SOFTWARE",
    unitPrice: 200,
    currency: "EUR",
    taxRate: 22,
    unit: "anno",
    isActive: false,
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-04-01T10:00:00Z",
  },
  {
    id: "prod-8",
    name: "Data Migration",
    code: "SVC-MIG-001",
    description: "Servizio di migrazione dati da sistemi legacy",
    category: "SERVICE",
    unitPrice: 1200,
    currency: "EUR",
    taxRate: 22,
    unit: "progetto",
    isActive: true,
    createdAt: "2024-04-05T10:00:00Z",
    updatedAt: "2024-04-05T10:00:00Z",
  },
];

function makeDealProduct(
  id: string,
  dealId: string,
  product: Product,
  quantity: number,
  discount = 0,
  note?: string
): DealProduct {
  const subtotal = product.unitPrice * quantity * (1 - discount / 100);
  const total = subtotal * (1 + product.taxRate / 100);
  return {
    id,
    dealId,
    product,
    quantity,
    unitPrice: product.unitPrice,
    discount,
    taxRate: product.taxRate,
    currency: product.currency,
    subtotal,
    total,
    note: note ?? null,
    addedAt: "2024-04-10T10:00:00Z",
  };
}

export const MOCK_DEAL_PRODUCTS: DealProduct[] = [
  makeDealProduct("dp-1", "deal-1", MOCK_PRODUCTS[0]!, 1, 0),
  makeDealProduct("dp-2", "deal-1", MOCK_PRODUCTS[1]!, 10, 10, "Onboarding iniziale"),
  makeDealProduct("dp-3", "deal-2", MOCK_PRODUCTS[3]!, 12, 0),
  makeDealProduct("dp-4", "deal-3", MOCK_PRODUCTS[0]!, 3, 15, "Sconto volume 3 licenze"),
  makeDealProduct("dp-5", "deal-3", MOCK_PRODUCTS[2]!, 3, 0),
];
