/**
 * Mock data for development — used when DB is not connected.
 * Replace with real DB queries after running prisma migrate + seed.
 */
import type { Pipeline } from "@/types/deals";

const OWNER = { id: "owner-1", name: "Mario Rossi", email: "owner@acme.com" };
const SALES = { id: "sales-1", name: "Giulia Bianchi", email: "sales@acme.com" };

const now = new Date();
function daysAgo(n: number) {
  return new Date(now.getTime() - n * 86400000).toISOString();
}
function daysFromNow(n: number) {
  return new Date(now.getTime() + n * 86400000).toISOString();
}

export const MOCK_PIPELINE: Pipeline = {
  id: "pipeline-1",
  name: "Pipeline Principale",
  isDefault: true,
  stages: [
    {
      id: "stage-1",
      name: "Qualificazione",
      position: 0,
      probability: 20,
      rotting: 14,
      totalValue: 122000,
      deals: [
        {
          id: "deal-1",
          title: "Implementazione CRM - TechSolutions",
          value: 45000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-1",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: { id: "c1", firstName: "Marco", lastName: "Ferrari" },
          company: { id: "co1", name: "TechSolutions Srl" },
          expectedClose: daysFromNow(30),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(20),
          updatedAt: daysAgo(16),
          daysInStage: 16,
        },
        {
          id: "deal-2",
          title: "Progetto ERP - Global Industries",
          value: 77000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-1",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: { id: "c2", firstName: "Sara", lastName: "Russo" },
          company: { id: "co2", name: "Global Industries SpA" },
          expectedClose: daysFromNow(45),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(5),
          updatedAt: daysAgo(5),
          daysInStage: 5,
        },
      ],
    },
    {
      id: "stage-2",
      name: "Contatto",
      position: 1,
      probability: 40,
      rotting: 10,
      totalValue: 98000,
      deals: [
        {
          id: "deal-3",
          title: "Consulenza IT - Innovatech",
          value: 28000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-2",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: { id: "c3", firstName: "Luca", lastName: "Bianchi" },
          company: { id: "co3", name: "Innovatech Srl" },
          expectedClose: daysFromNow(20),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(12),
          updatedAt: daysAgo(11),
          daysInStage: 11,
        },
        {
          id: "deal-4",
          title: "Sviluppo App Mobile - Alpha",
          value: 35000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-2",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: { id: "c4", firstName: "Anna", lastName: "Romano" },
          company: { id: "co4", name: "Alpha Services" },
          expectedClose: daysFromNow(25),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(8),
          updatedAt: daysAgo(3),
          daysInStage: 3,
        },
        {
          id: "deal-5",
          title: "Migrazione Cloud - Beta",
          value: 35000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-2",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: null,
          company: { id: "co5", name: "Beta Consulting" },
          expectedClose: daysFromNow(15),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(3),
          updatedAt: daysAgo(3),
          daysInStage: 3,
        },
      ],
    },
    {
      id: "stage-3",
      name: "Proposta",
      position: 2,
      probability: 60,
      rotting: 7,
      totalValue: 210000,
      deals: [
        {
          id: "deal-6",
          title: "Sistema BI - Gamma Corp",
          value: 65000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-3",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: { id: "c5", firstName: "Paolo", lastName: "Esposito" },
          company: { id: "co6", name: "Gamma Corp" },
          expectedClose: daysFromNow(10),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(15),
          updatedAt: daysAgo(8),
          daysInStage: 8,
        },
        {
          id: "deal-7",
          title: "E-commerce Platform - Delta",
          value: 82000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-3",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: { id: "c6", firstName: "Marta", lastName: "Ricci" },
          company: { id: "co7", name: "Delta Systems" },
          expectedClose: daysFromNow(14),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(10),
          updatedAt: daysAgo(2),
          daysInStage: 2,
        },
        {
          id: "deal-8",
          title: "Automazione Marketing - Epsilon",
          value: 63000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-3",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: null,
          company: { id: "co8", name: "Epsilon Group" },
          expectedClose: daysFromNow(7),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(7),
          updatedAt: daysAgo(7),
          daysInStage: 7,
        },
      ],
    },
    {
      id: "stage-4",
      name: "Negoziazione",
      position: 3,
      probability: 80,
      rotting: 5,
      totalValue: 175000,
      deals: [
        {
          id: "deal-9",
          title: "Integrazione API - Zeta",
          value: 48000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-4",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: { id: "c7", firstName: "Giorgio", lastName: "Marino" },
          company: { id: "co9", name: "Zeta Holdings" },
          expectedClose: daysFromNow(5),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(20),
          updatedAt: daysAgo(6),
          daysInStage: 6,
        },
        {
          id: "deal-10",
          title: "Sicurezza IT - Eta Partners",
          value: 127000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-4",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: { id: "c8", firstName: "Elena", lastName: "Greco" },
          company: { id: "co10", name: "Eta Partners" },
          expectedClose: daysFromNow(3),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(18),
          updatedAt: daysAgo(1),
          daysInStage: 1,
        },
      ],
    },
    {
      id: "stage-5",
      name: "Chiusura",
      position: 4,
      probability: 95,
      rotting: 3,
      totalValue: 320000,
      deals: [
        {
          id: "deal-11",
          title: "Dashboard Analytics - Fabio",
          value: 95000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-5",
          pipelineId: "pipeline-1",
          ownerId: OWNER.id,
          owner: OWNER,
          contact: { id: "c9", firstName: "Fabio", lastName: "Bruno" },
          company: null,
          expectedClose: daysFromNow(2),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(25),
          updatedAt: daysAgo(4),
          daysInStage: 4,
        },
        {
          id: "deal-12",
          title: "Software HR - Chiara",
          value: 225000,
          currency: "EUR",
          status: "OPEN",
          stageId: "stage-5",
          pipelineId: "pipeline-1",
          ownerId: SALES.id,
          owner: SALES,
          contact: { id: "c10", firstName: "Chiara", lastName: "Gallo" },
          company: { id: "co1", name: "TechSolutions Srl" },
          expectedClose: daysFromNow(1),
          closedAt: null,
          lostReason: null,
          createdAt: daysAgo(30),
          updatedAt: daysAgo(0),
          daysInStage: 0,
        },
      ],
    },
  ],
};

export const MOCK_PIPELINES: Pipeline[] = [MOCK_PIPELINE];
